# Generated by Django 3.0.2 on 2020-01-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='choice_test',
            new_name='answers_set',
        ),
    ]
